//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LVL { get; set; }
        public Nullable<int> EXP { get; set; }
        public Nullable<int> STR { get; set; }
        public Nullable<int> INT { get; set; }
        public Nullable<int> STM { get; set; }
        public Nullable<double> ATK { get; set; }
        public Nullable<double> WATK { get; set; }
        public Nullable<int> HEALTH { get; set; }
        public Nullable<int> CASH { get; set; }
    }
}
